server:
  port: 8089
spring:
  application:
    name: ai-mak-agent
  ai:
    mcp:
      server:
        enabled: true
        version: 1.0.0
        name: mak-mcp-server
        type: sync
        instructions: "This server provides weather information tools and resources"
#        capabilities:
#          tool: true
#          resource: true
#          prompt: true
#          completion: true
#        sse-endpoint: /mcp/sse
#        sse-message-endpoint: /mcp/message
